apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-extra-scrape
  namespace: monitoring
data:
  peag-scrape.yml: |
    - job_name: 'peag-gateway'
      static_configs:
        - targets: ['peag-gateway.ai.svc.cluster.local:8000']
      metrics_path: '/metrics/'
      scrape_interval: 15s
